language: node_js
matrix:
 include:
  - node_js: "8"
    env: GULP_TASK="test-docs-travis" JEKYLL_ENV="testing"
 fast_finish: true

before_install:
   - rvm install 2.5.1
   - curl -o- -L https://yarnpkg.com/install.sh | bash
   - export PATH=$HOME/.yarn/bin:$PATH
   - yarn install

cache: yarn

install: bundle install

branches:
  except:
    - /^build-bot-temp-.*$/

notifications:
 email: false
