trigger:
  branches:
    exclude:
    - build-bot-temp-*
    - (testbot-only)*
    - new-docs

  paths:
    include:
    - /bin
    - /src
    - /test
    - /azure-pipelines.yml
    - /Gulpfile.js
    - /package.json

pool: 'BrowserStack agents'

variables:
  RETRY_FAILED_TESTS: "true"

steps:
- bash: |
    if [[ $BUILD_SOURCEVERSIONMESSAGE =~ ^\[docs\] ]] || [[ ! -f "appveyor.yml" ]]; then
      echo '##vso[task.setvariable variable=isDocCommit]true'
    fi
  displayName: 'Check commit type'

- task: NodeTool@0
  displayName: 'Install Node.js'
  condition: and(succeeded(), not(variables['isDocCommit']))
  timeoutInMinutes: 40
  inputs:
    versionSpec: '10.x'

- bash: |
    npm install --no-progress --loglevel error
    npm test
  displayName: 'Run tests'
  condition: and(succeeded(), not(variables['isDocCommit']))
  timeoutInMinutes: 60
